version: "2"
services:
    web:
        build: .
        volumes:
            - ./:/app
        ports:
            - "3000:3000"
        links:
            - mongo
        environment:
            - MONGO_URI=mongodb://mongo:27017/app
    mongo:
        image: mongo
        ports:
            - "27017:27017"
